language: java
sudo: required
before_script:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- sleep 3
- psql -c 'create database test_db;' -U postgres
services:
    - postgresql
script:
- mvn clean install
- mvn test